kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-dev--mysql-data-0
  labels:
    type: local
spec:
  storageClassName: slurm-dev--mysql-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /scratch/slurm-dev/database/mysql-0/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-dev01


---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-dev--mysql-data-1
  labels:
    type: local
spec:
  storageClassName: slurm-dev--mysql-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /scratch/slurm-dev/database/mysql-1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-dev01

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-dev--mysql-data-2
  labels:
    type: local
spec:
  storageClassName: slurm-dev--mysql-data
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /scratch/slurm-dev/database/mysql-2/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-dev01

