apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  template:
    spec:
      nodeSelector:
        group: infra
        slurm: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurmdbd
spec:
  template:
    spec:
      nodeSelector:
        group: infra

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  template:
    spec:
      nodeSelector:
        group: infra
