---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-dev--slurmctld-data"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: spool
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-dev--slurmctld-spool"
      resources:
        requests:
          storage: 1Gi

---
