apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slurm-dev

configMapGenerator:
- name: slurmdbd-config
  files:
  - etc/slurmdbd.conf
- name: slurmctld-config
  files:
  - etc/slurm.conf
  - etc/job_submit.lua
  - etc/slac.conf
  - etc/gres.conf
  - etc/cgroup.conf
  - etc/cgroup_allowed_devices_file.conf

secretGenerator:
- name: munge
  behavior: replace
  files:
  - munge.key

resources:
- kubernetes/ns.yaml
- kubernetes/database-storage.yaml
- kubernetes/secrets.yaml
- kubernetes/database.yaml
- kubernetes/slurmdbd.yaml
- kubernetes/slurmctld-storage.yaml
- kubernetes/slurmctld.yaml

patchesStrategicMerge:
- nodeSelectors.yaml
- metallb.yaml
- loadBalancer.yaml

images:
- name: slaclab/slurm-docker
  newTag: '20191209.1'

commonLabels:
  app: slurm
  env: dev
