apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slurm-dev

configMapGenerator:
- name: slurm-config
  files:
  - slurm.conf
  - gres.conf
  - cgroup.conf
  - slurmdbd.conf

secretGenerator:
- name: munge
  behavior: replace
  files:
  - munge.key

resources:
- kubernetes/ns.yaml
- kubernetes/database-storage.yaml
- kubernetes/secrets.yaml
- kubernetes/database.yaml
- kubernetes/slurmdbd.yaml
- kubernetes/slurmctld.yaml

patchesStrategicMerge:
- nodeSelectors.yaml
- metallb.yaml
- loadBalancer.yaml

images:
- name: slaclab/slurm-docker
  newTag: '20190821.3'

commonLabels:
  app: slurm
  env: dev
