apiVersion: v1
kind: Service
metadata:
  name: slurmdbd-0
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: slurm-dev
---

apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: slurm-dev
    
