apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slurm

resources:
#- database.yaml
- database-cm.yaml
- database-sts.yaml
- slurmdbd.yaml
- slurmctld.yaml

#images:
#- name: slaclab/slurm-docker
#  newTag: '20191219.0'

commonLabels:
  app: slurm
