apiVersion: v1
kind: Service
metadata:
  name: slurmctld-0
  labels:
    role: slurmctld
    rank: primary
spec:
  type: LoadBalancer
  ports:
  - name: slurmctld
    protocol: TCP
    port: 6817
  selector:
    role: slurmctld
    statefulset.kubernetes.io/pod-name: slurmctld-0
---

apiVersion: v1
kind: Service
metadata:
  name: slurmctld-1
  labels:
    role: slurmctld
    rank: secondary
spec:
  type: LoadBalancer
  ports:
  - name: slurmctld
    protocol: TCP
    port: 6817
  selector:
    role: slurmctld
    statefulset.kubernetes.io/pod-name: slurmctld-1

---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  selector:
    matchLabels:
      role: slurmctld
  serviceName: slurmctld
  replicas: 2
  template:
    metadata:
      labels:
        role: slurmctld
        rank: primary
    spec:
      containers:
      - name: slurmctld
        image: slaclab/slurm-docker:latest
        env:
        - name: SUPERVISORD_CONFIG
          value: "/etc/slurmctld-supervisord.conf"
        - name: SLURMCTLD_ARGS
          value: "-v"
        ports:
        - containerPort: 6817
          name: slurmctld
        volumeMounts:
        - name: slurmctld-config
          mountPath: /etc/slurm
        - name: munge-key
          mountPath: "/mnt/munge"
          readOnly: true
        - name: data
          mountPath: /var/lib/slurmd/
        - name: spool
          mountPath: /var/spool/slurmd/
        readinessProbe:
          exec:
            command:
            - pidof
            - slurmctld
          #tcpSocket:
          #  port: 6817
          initialDelaySeconds: 10 
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "if [ `ss -nlp -H '( sport = 6817 )' | wc -l` == 1 ]; then exit 0; else exit 127; fi"
          #tcpSocket:
          #  port: 6817
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: slurmctld-config
        configMap:
          name: slurmctld-config
          items:
          - key: slurm.conf
            path: slurm.conf
          - key: job_submit.lua
            path: job_submit.lua
          - key: slac.conf
            path: slac.conf
          - key: gres.conf
            path: gres.conf
          - key: cgroup.conf
            path: cgroup.conf
      - name: munge-key
        secret:
          secretName: munge
          defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-dev--slurmctld-data"
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: spool
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-dev--slurmctld-spool"
      resources:
 
