---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: slurm
  name: mysql
spec:
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: slurm-prod--mysql-data

---
