---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-prod--slurmctld-data"
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: spool
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "slurm-prod--slurmctld-spool"
      resources:
        requests:
          storage: 10Gi

---
