kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-dev--mysql-data
  labels:
    type: local
spec:
  storageClassName: slurm-dev--mysql-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /scratch/slurm/

