apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
  labels:
    app: slurmdbd
  annotations:
    metallb.universe.tf/address-pool: internal
spec:
  type: LoadBalancer
  ports:
  - name: slurmdbd
    port: 6819
  selector:
    app: slurmdbd

---

apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: slurmdbd
spec:
  selector:
    matchLabels:
      app: slurmdbd
  serviceName: slurmdbd
  replicas: 1
  template:
    metadata:
      labels:
        app: slurmdbd
    spec:
      nodeSelector:
$(list=(${slurmdbd__nodeSelectors// / }); for k in "${!list[@]}"; do kv=(${list[k]//\=/ }); echo "        ${kv[0]}: ${kv[1]}"; done)
      containers:
      - name: slurmdbd
        image: slaclab/slurm-docker:${slurmdbd_tag}
        env:
        - name: SUPERVISORD_CONFIG
          value: "/etc/slurmdbd-supervisord.conf"
        ports:
        - containerPort: 6819
        readinessProbe:
          tcpSocket:
            port: 6819
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6819
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm
        - name: munge-key
          mountPath: "/mnt/munge"
          readOnly: true
      volumes:
      - name: slurm-config
        configMap:
          name: slurm-config
          items:
          - key: slurm.conf
            path: slurm.conf
          - key: slurmdbd.conf
            path: slurmdbd.conf
      - name: munge-key
        secret:
          secretName: munge
          defaultMode: 256


