apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  labels:
    app: slurmctld
spec:
  type: LoadBalancer
  #type: ClusterIP
  ports:
  - name: slurmctld
    protocol: TCP
    port: 6817
  selector:
    role: slurmctld

---

apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  selector:
    matchLabels:
      role: slurmctld
  serviceName: slurmctld 
  replicas: 1
  template:
    metadata:
      labels:
        role: slurmctld
    spec:
      containers:
      - name: slurmctld
        image: slaclab/slurm-docker:latest
        ports:
        - containerPort: 6817
          name: slurmctld
        volumeMounts:
        - name: slurmctld-config
          mountPath: /etc/slurm
        - name: munge-key
          mountPath: "/mnt/munge"
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: 6817
          initialDelaySeconds: 10 
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6817
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: slurmctld-config
        configMap:
          name: slurmctld-config
          items:
          - key: slurm.conf
            path: slurm.conf
          - key: slac.conf
            path: slac.conf
          - key: gres.conf
            path: gres.conf
          - key: cgroup.conf
            path: cgroup.conf
      - name: munge-key
        secret:
          secretName: munge
          defaultMode: 256
  volumeClaimTemplates: []
