apiVersion: v1
kind: Service
metadata:
  name: slurmdbd-0
  labels:
    app: slurmdbd
    rank: primary
spec:
  type: LoadBalancer
  ports:
  - name: slurmdbd
    port: 6819
  selector:
    role: slurmdbd
    rank: primary

---

apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: slurmdbd
spec:
  selector:
    matchLabels:
      role: slurmdbd
      rank: primary
  serviceName: slurmdbd
  replicas: 1
  template:
    metadata:
      labels:
        role: slurmdbd
        rank: primary
    spec:
      containers:
      - name: slurmdbd
        image: slaclab/slurm-docker:latest
        env:
        - name: SUPERVISORD_CONFIG
          value: "/etc/slurmdbd-supervisord.conf"
        - name: SLURMDBD_ARGS
          value: "-v"
        ports:
        - containerPort: 6819
        readinessProbe:
          tcpSocket:
            port: 6819
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6819
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: slurmdbd-config
          mountPath: /etc/slurm
        - name: munge-key
          mountPath: "/mnt/munge"
          readOnly: true
      volumes:
      - name: slurmdbd-config
        configMap:
          name: slurmdbd-config
          items:
          - key: slurmdbd.conf
            path: slurmdbd.conf
      - name: munge-key
        secret:
          secretName: munge
          defaultMode: 256
  # TODO: add stateful volume
  volumeClaimTemplates: []
