apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  labels:
    app: slurmctld
  annotations:
    metallb.universe.tf/address-pool: internal
spec:
  type: LoadBalancer
  #type: ClusterIP
  ports:
  - name: slurmctld
    protocol: TCP
    port: 6817
  selector:
    app: slurmctld

---

apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: slurmctld
spec:
  selector:
    matchLabels:
      app: slurmctld
  serviceName: slurmctld 
  replicas: 1
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      nodeSelector:
$(list=(${slurmctld__nodeSelectors// / }); for k in "${!list[@]}"; do kv=(${list[k]//\=/ }); echo "        ${kv[0]}: ${kv[1]}"; done)
      containers:
      - name: slurmctld
        image: slaclab/slurm-docker:${slurmctld_tag}
        ports:
        - containerPort: 6817
          name: slurmctld
        volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm
        - name: munge-key
          mountPath: "/mnt/munge"
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: 6817
          initialDelaySeconds: 10 
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6817
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: slurm-config
        configMap:
          name: slurm-config
          items:
          - key: slurm.conf
            path: slurm.conf
          - key: gres.conf
            path: gres.conf
          - key: cgroup.conf
            path: cgroup.conf
      - name: munge-key
        secret:
          secretName: munge
          defaultMode: 256
