kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-prod--slurmctld-data
  labels:
    type: local
spec:
  storageClassName: slurm-prod--slurmctld-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /scratch/slurm/slurmctld/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-dev01

